---
- name: Mass Install
  hosts: all
  roles:
    - gui-tools
  vars:
    - install_bitwarden: true
    - install_vscode: true
    - install_simplescreenrecorder: true
    - install_flameshot: true
    - install_guake: true
    - install_slack: true
    - install_zoom: true
    - install_zulucrypt_gui: true
    - install_virtualbox: true
    - install_redshift: true
    - flameshot_autostart: true

- name: Mass Install CLI
  hosts: all
  roles:
    - cli-tools
  vars:
    - install_zsh: true
    - install_htop: true
    - install_vagrant: true
    - install_tldr: true
    - install_tree: true
    - install_yt_dlp: true
    # Need to manually set Ubuntu release for vagrant
    - ansible_distribution_release: "jammy"